export const constants = {
    HUB_URL: "",
    STORAGE_KEY: "[IdentityService] STORAGE_KEY",
    ACCESS_TOKEN_KEY: "ACCESS TOKEN_KEY",
    LOGIN_CREDENTIALS: "LOGIN CREDENTIALS",
    TENANT: "TENANT",
    CORRELATION_IDS_KEY: "CORRELATION IDS KEY"
};